#!/usr/bin/env node
/**
 * Liara Engine — generates a default astro.config.mjs when a module
 * doesn't ship one of its own.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readManifest, readRegistry } from '../index.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '..', 'astro.config.mjs');

if (existsSync(target)) {
    console.log(`[config] ${target} already present — leaving it alone`);
    process.exit(0);
}

const repo = process.env.LIARA_DOCS_REPO;
if (!repo) {
    console.log('[config] LIARA_DOCS_REPO is not set — nothing to generate a config from');
    process.exit(0);
}

const manifest = readManifest();
const registryEntry = (readRegistry().modules ?? []).find((module) => module.repo === repo) ?? null;

const title = manifest?.metadata?.name || registryEntry?.name || repo;
const description = manifest?.metadata?.description || `Documentation for ${title}.`;
const hasApi = process.env.LIARA_DOCS_API === 'true';

const config = `\
// Generated by @liara/starlight-preset/scripts/generate-config.mjs: ${repo}
// does not ship its own astro.config.mjs. Commit a real one at the
// repository root to override any or all of this — see
// docs/authoring-a-module.md.
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { liaraDocs } from '@liara/starlight-preset';

export default defineConfig(liaraDocs({
    starlight,
    repo: ${JSON.stringify(repo)},
    title: ${JSON.stringify(title)},
    description: ${JSON.stringify(description)},
    api: ${hasApi},
}));
`;

writeFileSync(target, config);
console.log(`[config] generated ${target} for ${repo} `
    + `(title: ${JSON.stringify(title)}, api: ${hasApi})`);
