name: shared

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-shared.yml'
      - 'shared-content/**'
  workflow_dispatch:

jobs:
  build:
    uses: liara-engine/.github/.github/workflows/reusable-build-docs.yml@v0
    with:
      image: ghcr.io/liara-engine/liara-documentation-builder:latest
      additional-dir-to-deploy: "shared-content"

    secrets:
      ghcr-token: ${{ secrets.GITHUB_TOKEN }}
      push-token: ${{ secrets.DOCS_PUSH_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    concurrency:
      group: docs-publish-${{ github.repository }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          repository: liara-engine/liara-docs
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: output-repository
          fetch-depth: '0'

      - run: |
          cd output-repository
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cd ..

      - name: Prepare output branch
        run: |
          cd output-repository
          output_branch="cloudflare-pages"

          if git ls-remote --exit-code --heads origin $output_branch; then
              echo "Branch exists"
              git checkout $output_branch
              git pull origin $output_branch
          else
              echo "Branch does not exist, creating it"
              git checkout --orphan $output_branch
              git rm -rf . || true
              echo "# Documentation" > README.md
              mkdir -p site
              echo "<DOCTYPE html><html><head><title>Documentation</title></head><body><h1>Documentation</h1><p>This branch is used to host generated documentation.</p></body></html>" > site/index.html
              git add README.md
              git commit -m "Initialize documentation branch"
              git push origin $output_branch
          fi

      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: generated-docs

      - run: |
          output_dir="output-repository/site/shared-content"
          mkdir -p "$output_dir"
          rm -rf "$output_dir/*"
          cp -r generated-docs/shared-content/* "$output_dir/"

      - run: |
          cd output-repository
          git add site/shared-content
          git commit -m "Update shared content"
          git push origin HEAD